# Generated by Django 4.2 on 2023-07-30 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentReportCard', '0002_alter_subjectmarks_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rank', models.IntegerField()),
                ('date_of_generating_report', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rank', to='StudentReportCard.student')),
            ],
            options={
                'unique_together': {('student_rank', 'date_of_generating_report')},
            },
        ),
    ]
