# Generated by Django 4.2 on 2023-07-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentReportCard', '0003_student_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
